

struct DataLine
{
	sequence<string> value;
};
typedef sequence<DataLine> DataList;

module DataBase {
	interface mDataBase
	{
		string get_value(in string l, in string c, in string sn);
		void set_value(in string l, in string c, in string sn, in string v);

		DataList get_value_range(in string l, in string c, in string sn);
		void set_value_range(in string l, in string c, in string sn, in DataList v);
	};
};